/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevStatusBannerRouteImport } from './routes/dev/status-banner'
import { Route as DevIconsRouteImport } from './routes/dev/icons'
import { Route as DevFormElementsRouteImport } from './routes/dev/form-elements'
import { Route as DevDraggableRouteImport } from './routes/dev/draggable'
import { Route as DevCardsRouteImport } from './routes/dev/cards'
import { Route as DevButtonRouteImport } from './routes/dev/button'
import { Route as DevBadgeRouteImport } from './routes/dev/badge'
import { Route as DevAccordionRouteImport } from './routes/dev/accordion'
import { Route as ApplicationsIdRouteImport } from './routes/applications.$id'
import { Route as AccountNotificationsRouteImport } from './routes/account_.notifications'
import { Route as ServicesServiceIdIndexRouteImport } from './routes/services.$serviceId.index'
import { Route as ServicesServiceIdVersionsVersionIdRouteImport } from './routes/services.$serviceId.versions.$versionId'
import { Route as ServicesServiceIdApplyFormIdRouteImport } from './routes/services.$serviceId.apply.$formId'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevStatusBannerRoute = DevStatusBannerRouteImport.update({
  id: '/status-banner',
  path: '/status-banner',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevIconsRoute = DevIconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevFormElementsRoute = DevFormElementsRouteImport.update({
  id: '/form-elements',
  path: '/form-elements',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevDraggableRoute = DevDraggableRouteImport.update({
  id: '/draggable',
  path: '/draggable',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevCardsRoute = DevCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevButtonRoute = DevButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevBadgeRoute = DevBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevAccordionRoute = DevAccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => DevRouteRoute,
} as any)
const ApplicationsIdRoute = ApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account_/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdIndexRoute = ServicesServiceIdIndexRouteImport.update({
  id: '/services/$serviceId/',
  path: '/services/$serviceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdVersionsVersionIdRoute =
  ServicesServiceIdVersionsVersionIdRouteImport.update({
    id: '/services/$serviceId/versions/$versionId',
    path: '/services/$serviceId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesServiceIdApplyFormIdRoute =
  ServicesServiceIdApplyFormIdRouteImport.update({
    id: '/services/$serviceId/apply/$formId',
    path: '/services/$serviceId/apply/$formId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/dev/accordion': typeof DevAccordionRoute
  '/dev/badge': typeof DevBadgeRoute
  '/dev/button': typeof DevButtonRoute
  '/dev/cards': typeof DevCardsRoute
  '/dev/draggable': typeof DevDraggableRoute
  '/dev/form-elements': typeof DevFormElementsRoute
  '/dev/icons': typeof DevIconsRoute
  '/dev/status-banner': typeof DevStatusBannerRoute
  '/dev/': typeof DevIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
  '/services/$serviceId/apply/$formId': typeof ServicesServiceIdApplyFormIdRoute
  '/services/$serviceId/versions/$versionId': typeof ServicesServiceIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/dev/accordion': typeof DevAccordionRoute
  '/dev/badge': typeof DevBadgeRoute
  '/dev/button': typeof DevButtonRoute
  '/dev/cards': typeof DevCardsRoute
  '/dev/draggable': typeof DevDraggableRoute
  '/dev/form-elements': typeof DevFormElementsRoute
  '/dev/icons': typeof DevIconsRoute
  '/dev/status-banner': typeof DevStatusBannerRoute
  '/dev': typeof DevIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$serviceId': typeof ServicesServiceIdIndexRoute
  '/services/$serviceId/apply/$formId': typeof ServicesServiceIdApplyFormIdRoute
  '/services/$serviceId/versions/$versionId': typeof ServicesServiceIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/account_/notifications': typeof AccountNotificationsRoute
  '/applications/$id': typeof ApplicationsIdRoute
  '/dev/accordion': typeof DevAccordionRoute
  '/dev/badge': typeof DevBadgeRoute
  '/dev/button': typeof DevButtonRoute
  '/dev/cards': typeof DevCardsRoute
  '/dev/draggable': typeof DevDraggableRoute
  '/dev/form-elements': typeof DevFormElementsRoute
  '/dev/icons': typeof DevIconsRoute
  '/dev/status-banner': typeof DevStatusBannerRoute
  '/dev/': typeof DevIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
  '/services/$serviceId/apply/$formId': typeof ServicesServiceIdApplyFormIdRoute
  '/services/$serviceId/versions/$versionId': typeof ServicesServiceIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/account'
    | '/account/notifications'
    | '/applications/$id'
    | '/dev/accordion'
    | '/dev/badge'
    | '/dev/button'
    | '/dev/cards'
    | '/dev/draggable'
    | '/dev/form-elements'
    | '/dev/icons'
    | '/dev/status-banner'
    | '/dev/'
    | '/services/'
    | '/services/$serviceId/'
    | '/services/$serviceId/apply/$formId'
    | '/services/$serviceId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/account/notifications'
    | '/applications/$id'
    | '/dev/accordion'
    | '/dev/badge'
    | '/dev/button'
    | '/dev/cards'
    | '/dev/draggable'
    | '/dev/form-elements'
    | '/dev/icons'
    | '/dev/status-banner'
    | '/dev'
    | '/services'
    | '/services/$serviceId'
    | '/services/$serviceId/apply/$formId'
    | '/services/$serviceId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/dev'
    | '/account'
    | '/account_/notifications'
    | '/applications/$id'
    | '/dev/accordion'
    | '/dev/badge'
    | '/dev/button'
    | '/dev/cards'
    | '/dev/draggable'
    | '/dev/form-elements'
    | '/dev/icons'
    | '/dev/status-banner'
    | '/dev/'
    | '/services/'
    | '/services/$serviceId/'
    | '/services/$serviceId/apply/$formId'
    | '/services/$serviceId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRouteRoute: typeof DevRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  ApplicationsIdRoute: typeof ApplicationsIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesServiceIdIndexRoute: typeof ServicesServiceIdIndexRoute
  ServicesServiceIdApplyFormIdRoute: typeof ServicesServiceIdApplyFormIdRoute
  ServicesServiceIdVersionsVersionIdRoute: typeof ServicesServiceIdVersionsVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/status-banner': {
      id: '/dev/status-banner'
      path: '/status-banner'
      fullPath: '/dev/status-banner'
      preLoaderRoute: typeof DevStatusBannerRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/icons': {
      id: '/dev/icons'
      path: '/icons'
      fullPath: '/dev/icons'
      preLoaderRoute: typeof DevIconsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/form-elements': {
      id: '/dev/form-elements'
      path: '/form-elements'
      fullPath: '/dev/form-elements'
      preLoaderRoute: typeof DevFormElementsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/draggable': {
      id: '/dev/draggable'
      path: '/draggable'
      fullPath: '/dev/draggable'
      preLoaderRoute: typeof DevDraggableRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/cards': {
      id: '/dev/cards'
      path: '/cards'
      fullPath: '/dev/cards'
      preLoaderRoute: typeof DevCardsRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/button': {
      id: '/dev/button'
      path: '/button'
      fullPath: '/dev/button'
      preLoaderRoute: typeof DevButtonRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/badge': {
      id: '/dev/badge'
      path: '/badge'
      fullPath: '/dev/badge'
      preLoaderRoute: typeof DevBadgeRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/accordion': {
      id: '/dev/accordion'
      path: '/accordion'
      fullPath: '/dev/accordion'
      preLoaderRoute: typeof DevAccordionRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/applications/$id': {
      id: '/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof ApplicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/notifications': {
      id: '/account_/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/': {
      id: '/services/$serviceId/'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof ServicesServiceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/versions/$versionId': {
      id: '/services/$serviceId/versions/$versionId'
      path: '/services/$serviceId/versions/$versionId'
      fullPath: '/services/$serviceId/versions/$versionId'
      preLoaderRoute: typeof ServicesServiceIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/apply/$formId': {
      id: '/services/$serviceId/apply/$formId'
      path: '/services/$serviceId/apply/$formId'
      fullPath: '/services/$serviceId/apply/$formId'
      preLoaderRoute: typeof ServicesServiceIdApplyFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DevRouteRouteChildren {
  DevAccordionRoute: typeof DevAccordionRoute
  DevBadgeRoute: typeof DevBadgeRoute
  DevButtonRoute: typeof DevButtonRoute
  DevCardsRoute: typeof DevCardsRoute
  DevDraggableRoute: typeof DevDraggableRoute
  DevFormElementsRoute: typeof DevFormElementsRoute
  DevIconsRoute: typeof DevIconsRoute
  DevStatusBannerRoute: typeof DevStatusBannerRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevAccordionRoute: DevAccordionRoute,
  DevBadgeRoute: DevBadgeRoute,
  DevButtonRoute: DevButtonRoute,
  DevCardsRoute: DevCardsRoute,
  DevDraggableRoute: DevDraggableRoute,
  DevFormElementsRoute: DevFormElementsRoute,
  DevIconsRoute: DevIconsRoute,
  DevStatusBannerRoute: DevStatusBannerRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRouteRoute: DevRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  ApplicationsIdRoute: ApplicationsIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesServiceIdIndexRoute: ServicesServiceIdIndexRoute,
  ServicesServiceIdApplyFormIdRoute: ServicesServiceIdApplyFormIdRoute,
  ServicesServiceIdVersionsVersionIdRoute:
    ServicesServiceIdVersionsVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
