/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppSettingsConsentHistoryRouteRouteImport } from './routes/app/settings/consent-history/route'
import { Route as AppSettingsConsentHistoryIndexRouteImport } from './routes/app/settings/consent-history/index'
import { Route as AppServicesServiceSlugIndexRouteImport } from './routes/app/services/$serviceSlug/index'
import { Route as AppSettingsConsentHistoryStatementIdRouteImport } from './routes/app/settings/consent-history/$statementId'
import { Route as AppServicesServiceSlugApplyApplicationIdIndexRouteImport } from './routes/app/services/$serviceSlug/apply/$applicationId/index'
import { Route as AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport } from './routes/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsConsentHistoryRouteRoute =
  AppSettingsConsentHistoryRouteRouteImport.update({
    id: '/consent-history',
    path: '/consent-history',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsConsentHistoryIndexRoute =
  AppSettingsConsentHistoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSettingsConsentHistoryRouteRoute,
  } as any)
const AppServicesServiceSlugIndexRoute =
  AppServicesServiceSlugIndexRouteImport.update({
    id: '/services/$serviceSlug/',
    path: '/services/$serviceSlug/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsConsentHistoryStatementIdRoute =
  AppSettingsConsentHistoryStatementIdRouteImport.update({
    id: '/$statementId',
    path: '/$statementId',
    getParentRoute: () => AppSettingsConsentHistoryRouteRoute,
  } as any)
const AppServicesServiceSlugApplyApplicationIdIndexRoute =
  AppServicesServiceSlugApplyApplicationIdIndexRouteImport.update({
    id: '/services/$serviceSlug/apply/$applicationId/',
    path: '/services/$serviceSlug/apply/$applicationId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute =
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport.update({
    id: '/services/$serviceSlug/apply/$applicationId/data-and-privacy',
    path: '/services/$serviceSlug/apply/$applicationId/data-and-privacy',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dev/': typeof DevIndexRoute
  '/app/settings/consent-history': typeof AppSettingsConsentHistoryRouteRouteWithChildren
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/settings/consent-history/$statementId': typeof AppSettingsConsentHistoryStatementIdRoute
  '/app/services/$serviceSlug/': typeof AppServicesServiceSlugIndexRoute
  '/app/settings/consent-history/': typeof AppSettingsConsentHistoryIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId/': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/dev': typeof DevIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/consent-history/$statementId': typeof AppSettingsConsentHistoryStatementIdRoute
  '/app/services/$serviceSlug': typeof AppServicesServiceSlugIndexRoute
  '/app/settings/consent-history': typeof AppSettingsConsentHistoryIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dev/': typeof DevIndexRoute
  '/app/settings/consent-history': typeof AppSettingsConsentHistoryRouteRouteWithChildren
  '/app/services/': typeof AppServicesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/settings/consent-history/$statementId': typeof AppSettingsConsentHistoryStatementIdRoute
  '/app/services/$serviceSlug/': typeof AppServicesServiceSlugIndexRoute
  '/app/settings/consent-history/': typeof AppSettingsConsentHistoryIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId/': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/app'
    | '/app/settings'
    | '/'
    | '/admin/'
    | '/app/'
    | '/dev/'
    | '/app/settings/consent-history'
    | '/app/services/'
    | '/app/settings/'
    | '/app/settings/consent-history/$statementId'
    | '/app/services/$serviceSlug/'
    | '/app/settings/consent-history/'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/dev'
    | '/app/services'
    | '/app/settings'
    | '/app/settings/consent-history/$statementId'
    | '/app/services/$serviceSlug'
    | '/app/settings/consent-history'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId'
  id:
    | '__root__'
    | '/(public)'
    | '/admin'
    | '/app'
    | '/app/settings'
    | '/(public)/'
    | '/admin/'
    | '/app/'
    | '/dev/'
    | '/app/settings/consent-history'
    | '/app/services/'
    | '/app/settings/'
    | '/app/settings/consent-history/$statementId'
    | '/app/services/$serviceSlug/'
    | '/app/settings/consent-history/'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevIndexRoute: typeof DevIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/consent-history': {
      id: '/app/settings/consent-history'
      path: '/consent-history'
      fullPath: '/app/settings/consent-history'
      preLoaderRoute: typeof AppSettingsConsentHistoryRouteRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/consent-history/': {
      id: '/app/settings/consent-history/'
      path: '/'
      fullPath: '/app/settings/consent-history/'
      preLoaderRoute: typeof AppSettingsConsentHistoryIndexRouteImport
      parentRoute: typeof AppSettingsConsentHistoryRouteRoute
    }
    '/app/services/$serviceSlug/': {
      id: '/app/services/$serviceSlug/'
      path: '/services/$serviceSlug'
      fullPath: '/app/services/$serviceSlug/'
      preLoaderRoute: typeof AppServicesServiceSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/consent-history/$statementId': {
      id: '/app/settings/consent-history/$statementId'
      path: '/$statementId'
      fullPath: '/app/settings/consent-history/$statementId'
      preLoaderRoute: typeof AppSettingsConsentHistoryStatementIdRouteImport
      parentRoute: typeof AppSettingsConsentHistoryRouteRoute
    }
    '/app/services/$serviceSlug/apply/$applicationId/': {
      id: '/app/services/$serviceSlug/apply/$applicationId/'
      path: '/services/$serviceSlug/apply/$applicationId'
      fullPath: '/app/services/$serviceSlug/apply/$applicationId/'
      preLoaderRoute: typeof AppServicesServiceSlugApplyApplicationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': {
      id: '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      path: '/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      fullPath: '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      preLoaderRoute: typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppSettingsConsentHistoryRouteRouteChildren {
  AppSettingsConsentHistoryStatementIdRoute: typeof AppSettingsConsentHistoryStatementIdRoute
  AppSettingsConsentHistoryIndexRoute: typeof AppSettingsConsentHistoryIndexRoute
}

const AppSettingsConsentHistoryRouteRouteChildren: AppSettingsConsentHistoryRouteRouteChildren =
  {
    AppSettingsConsentHistoryStatementIdRoute:
      AppSettingsConsentHistoryStatementIdRoute,
    AppSettingsConsentHistoryIndexRoute: AppSettingsConsentHistoryIndexRoute,
  }

const AppSettingsConsentHistoryRouteRouteWithChildren =
  AppSettingsConsentHistoryRouteRoute._addFileChildren(
    AppSettingsConsentHistoryRouteRouteChildren,
  )

interface AppSettingsRouteRouteChildren {
  AppSettingsConsentHistoryRouteRoute: typeof AppSettingsConsentHistoryRouteRouteWithChildren
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsConsentHistoryRouteRoute:
    AppSettingsConsentHistoryRouteRouteWithChildren,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppServicesServiceSlugIndexRoute: typeof AppServicesServiceSlugIndexRoute
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute: typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  AppServicesServiceSlugApplyApplicationIdIndexRoute: typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppServicesServiceSlugIndexRoute: AppServicesServiceSlugIndexRoute,
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute:
    AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute,
  AppServicesServiceSlugApplyApplicationIdIndexRoute:
    AppServicesServiceSlugApplyApplicationIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  DevIndexRoute: DevIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
