/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicCallbackRouteImport } from './routes/(public)/callback'
import { Route as AppServicesIndexRouteImport } from './routes/app/services/index'
import { Route as AppServicesServiceSlugIndexRouteImport } from './routes/app/services/$serviceSlug/index'
import { Route as AppServicesServiceSlugApplyApplicationIdIndexRouteImport } from './routes/app/services/$serviceSlug/apply/$applicationId/index'
import { Route as AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport } from './routes/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCallbackRoute = publicCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => publicRouteRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesServiceSlugIndexRoute =
  AppServicesServiceSlugIndexRouteImport.update({
    id: '/services/$serviceSlug/',
    path: '/services/$serviceSlug/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppServicesServiceSlugApplyApplicationIdIndexRoute =
  AppServicesServiceSlugApplyApplicationIdIndexRouteImport.update({
    id: '/services/$serviceSlug/apply/$applicationId/',
    path: '/services/$serviceSlug/apply/$applicationId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute =
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport.update({
    id: '/services/$serviceSlug/apply/$applicationId/data-and-privacy',
    path: '/services/$serviceSlug/apply/$applicationId/data-and-privacy',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/callback': typeof publicCallbackRoute
  '/': typeof publicIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/services/$serviceSlug': typeof AppServicesServiceSlugIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof publicCallbackRoute
  '/': typeof publicIndexRoute
  '/app': typeof AppIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/services/$serviceSlug': typeof AppServicesServiceSlugIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/(public)/callback': typeof publicCallbackRoute
  '/(public)/': typeof publicIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/services/$serviceSlug/': typeof AppServicesServiceSlugIndexRoute
  '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  '/app/services/$serviceSlug/apply/$applicationId/': typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/callback'
    | '/'
    | '/app/'
    | '/app/services'
    | '/app/services/$serviceSlug'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/'
    | '/app'
    | '/app/services'
    | '/app/services/$serviceSlug'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId'
  id:
    | '__root__'
    | '/(public)'
    | '/app'
    | '/(public)/callback'
    | '/(public)/'
    | '/app/'
    | '/app/services/'
    | '/app/services/$serviceSlug/'
    | '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
    | '/app/services/$serviceSlug/apply/$applicationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/callback': {
      id: '/(public)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof publicCallbackRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/$serviceSlug/': {
      id: '/app/services/$serviceSlug/'
      path: '/services/$serviceSlug'
      fullPath: '/app/services/$serviceSlug'
      preLoaderRoute: typeof AppServicesServiceSlugIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/$serviceSlug/apply/$applicationId/': {
      id: '/app/services/$serviceSlug/apply/$applicationId/'
      path: '/services/$serviceSlug/apply/$applicationId'
      fullPath: '/app/services/$serviceSlug/apply/$applicationId'
      preLoaderRoute: typeof AppServicesServiceSlugApplyApplicationIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy': {
      id: '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      path: '/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      fullPath: '/app/services/$serviceSlug/apply/$applicationId/data-and-privacy'
      preLoaderRoute: typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicCallbackRoute: typeof publicCallbackRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicCallbackRoute: publicCallbackRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppServicesServiceSlugIndexRoute: typeof AppServicesServiceSlugIndexRoute
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute: typeof AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute
  AppServicesServiceSlugApplyApplicationIdIndexRoute: typeof AppServicesServiceSlugApplyApplicationIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppServicesServiceSlugIndexRoute: AppServicesServiceSlugIndexRoute,
  AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute:
    AppServicesServiceSlugApplyApplicationIdDataAndPrivacyRoute,
  AppServicesServiceSlugApplyApplicationIdIndexRoute:
    AppServicesServiceSlugApplyApplicationIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
