/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as AdminDocumentTypesRouteImport } from './routes/admin.document-types'
import { Route as AppSlugIndexRouteImport } from './routes/app.$slug.index'
import { Route as AppSlugTeamRouteImport } from './routes/app.$slug.team'
import { Route as AppSlugSubmissionsRouteImport } from './routes/app.$slug.submissions'
import { Route as AppSlugSettingsRouteImport } from './routes/app.$slug.settings'
import { Route as AppSlugServicesRouteImport } from './routes/app.$slug.services'
import { Route as AppSlugReportsRouteImport } from './routes/app.$slug.reports'
import { Route as AppSlugApplicationsRouteImport } from './routes/app.$slug.applications'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminDocumentTypesRoute = AdminDocumentTypesRouteImport.update({
  id: '/document-types',
  path: '/document-types',
  getParentRoute: () => AdminRoute,
} as any)
const AppSlugIndexRoute = AppSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugTeamRoute = AppSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugSubmissionsRoute = AppSlugSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugSettingsRoute = AppSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugServicesRoute = AppSlugServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugReportsRoute = AppSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugApplicationsRoute = AppSlugApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/$slug/applications': typeof AppSlugApplicationsRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/services': typeof AppSlugServicesRoute
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsRoute
  '/app/$slug/team': typeof AppSlugTeamRoute
  '/app/$slug/': typeof AppSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/app/account': typeof AppAccountRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/$slug/applications': typeof AppSlugApplicationsRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/services': typeof AppSlugServicesRoute
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsRoute
  '/app/$slug/team': typeof AppSlugTeamRoute
  '/app/$slug': typeof AppSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/document-types': typeof AdminDocumentTypesRoute
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/$slug/applications': typeof AppSlugApplicationsRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/services': typeof AppSlugServicesRoute
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsRoute
  '/app/$slug/team': typeof AppSlugTeamRoute
  '/app/$slug/': typeof AppSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/document-types'
    | '/app/$slug'
    | '/app/account'
    | '/admin/'
    | '/app/'
    | '/app/$slug/applications'
    | '/app/$slug/reports'
    | '/app/$slug/services'
    | '/app/$slug/settings'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/app/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/document-types'
    | '/app/account'
    | '/admin'
    | '/app'
    | '/app/$slug/applications'
    | '/app/$slug/reports'
    | '/app/$slug/services'
    | '/app/$slug/settings'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/app/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/document-types'
    | '/app/$slug'
    | '/app/account'
    | '/admin/'
    | '/app/'
    | '/app/$slug/applications'
    | '/app/$slug/reports'
    | '/app/$slug/services'
    | '/app/$slug/settings'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/app/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/document-types': {
      id: '/admin/document-types'
      path: '/document-types'
      fullPath: '/admin/document-types'
      preLoaderRoute: typeof AdminDocumentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/$slug/': {
      id: '/app/$slug/'
      path: '/'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AppSlugIndexRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/team': {
      id: '/app/$slug/team'
      path: '/team'
      fullPath: '/app/$slug/team'
      preLoaderRoute: typeof AppSlugTeamRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/submissions': {
      id: '/app/$slug/submissions'
      path: '/submissions'
      fullPath: '/app/$slug/submissions'
      preLoaderRoute: typeof AppSlugSubmissionsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/settings': {
      id: '/app/$slug/settings'
      path: '/settings'
      fullPath: '/app/$slug/settings'
      preLoaderRoute: typeof AppSlugSettingsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/services': {
      id: '/app/$slug/services'
      path: '/services'
      fullPath: '/app/$slug/services'
      preLoaderRoute: typeof AppSlugServicesRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/reports': {
      id: '/app/$slug/reports'
      path: '/reports'
      fullPath: '/app/$slug/reports'
      preLoaderRoute: typeof AppSlugReportsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/applications': {
      id: '/app/$slug/applications'
      path: '/applications'
      fullPath: '/app/$slug/applications'
      preLoaderRoute: typeof AppSlugApplicationsRouteImport
      parentRoute: typeof AppSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentTypesRoute: typeof AdminDocumentTypesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentTypesRoute: AdminDocumentTypesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppSlugRouteChildren {
  AppSlugApplicationsRoute: typeof AppSlugApplicationsRoute
  AppSlugReportsRoute: typeof AppSlugReportsRoute
  AppSlugServicesRoute: typeof AppSlugServicesRoute
  AppSlugSettingsRoute: typeof AppSlugSettingsRoute
  AppSlugSubmissionsRoute: typeof AppSlugSubmissionsRoute
  AppSlugTeamRoute: typeof AppSlugTeamRoute
  AppSlugIndexRoute: typeof AppSlugIndexRoute
}

const AppSlugRouteChildren: AppSlugRouteChildren = {
  AppSlugApplicationsRoute: AppSlugApplicationsRoute,
  AppSlugReportsRoute: AppSlugReportsRoute,
  AppSlugServicesRoute: AppSlugServicesRoute,
  AppSlugSettingsRoute: AppSlugSettingsRoute,
  AppSlugSubmissionsRoute: AppSlugSubmissionsRoute,
  AppSlugTeamRoute: AppSlugTeamRoute,
  AppSlugIndexRoute: AppSlugIndexRoute,
}

const AppSlugRouteWithChildren =
  AppSlugRoute._addFileChildren(AppSlugRouteChildren)

interface AppRouteChildren {
  AppSlugRoute: typeof AppSlugRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSlugRoute: AppSlugRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
