/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AppSlugRouteImport } from './routes/app.$slug'
import { Route as AdminServiceAgreementsRouteImport } from './routes/admin.service-agreements'
import { Route as AdminDocumentTypesRouteImport } from './routes/admin.document-types'
import { Route as AppSlugIndexRouteImport } from './routes/app.$slug.index'
import { Route as AdminServiceAgreementsIndexRouteImport } from './routes/admin.service-agreements.index'
import { Route as AdminDocumentTypesIndexRouteImport } from './routes/admin.document-types.index'
import { Route as AppSlugTeamRouteImport } from './routes/app.$slug.team'
import { Route as AppSlugSubmissionsRouteImport } from './routes/app.$slug.submissions'
import { Route as AppSlugSettingsRouteImport } from './routes/app.$slug.settings'
import { Route as AppSlugServicesRouteImport } from './routes/app.$slug.services'
import { Route as AppSlugServiceAgreementsRouteImport } from './routes/app.$slug.service-agreements'
import { Route as AppSlugReportsRouteImport } from './routes/app.$slug.reports'
import { Route as AdminServiceAgreementsNewRouteImport } from './routes/admin.service-agreements.new'
import { Route as AdminServiceAgreementsIdRouteImport } from './routes/admin.service-agreements.$id'
import { Route as AdminDocumentTypesIdRouteImport } from './routes/admin.document-types.$id'
import { Route as AppSlugTeamIndexRouteImport } from './routes/app.$slug.team.index'
import { Route as AppSlugSubmissionsIndexRouteImport } from './routes/app.$slug.submissions.index'
import { Route as AppSlugServicesIndexRouteImport } from './routes/app.$slug.services.index'
import { Route as AppSlugServiceAgreementsIndexRouteImport } from './routes/app.$slug.service-agreements.index'
import { Route as AppSlugTeamMemberIdRouteImport } from './routes/app.$slug.team.$memberId'
import { Route as AppSlugSubmissionsIdRouteImport } from './routes/app.$slug.submissions.$id'
import { Route as AppSlugServicesNewRouteImport } from './routes/app.$slug.services.new'
import { Route as AppSlugServicesIdRouteImport } from './routes/app.$slug.services.$id'
import { Route as AppSlugServiceAgreementsNewRouteImport } from './routes/app.$slug.service-agreements.new'
import { Route as AppSlugServiceAgreementsIdRouteImport } from './routes/app.$slug.service-agreements.$id'
import { Route as AppSlugServicesIdIndexRouteImport } from './routes/app.$slug.services.$id.index'
import { Route as AppSlugServicesIdServiceAgreementsRouteImport } from './routes/app.$slug.services.$id.service-agreements'
import { Route as AppSlugServicesIdApplicationMethodsRouteImport } from './routes/app.$slug.services.$id.application-methods'
import { Route as AppSlugServicesIdVersionsVersionIdIndexRouteImport } from './routes/app.$slug.services.$id.versions.$versionId.index'
import { Route as AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRouteImport } from './routes/app.$slug.services.$id.versions.$versionId.service-agreements.index'
import { Route as AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRouteImport } from './routes/app.$slug.services.$id.versions.$versionId.application-methods.index'
import { Route as AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRouteImport } from './routes/app.$slug.services.$id.versions.$versionId.application-methods.new'
import { Route as AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRouteImport } from './routes/app.$slug.services.$id.versions.$versionId.application-methods.$applicationMethodId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminServiceAgreementsRoute = AdminServiceAgreementsRouteImport.update({
  id: '/service-agreements',
  path: '/service-agreements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentTypesRoute = AdminDocumentTypesRouteImport.update({
  id: '/document-types',
  path: '/document-types',
  getParentRoute: () => AdminRoute,
} as any)
const AppSlugIndexRoute = AppSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugRoute,
} as any)
const AdminServiceAgreementsIndexRoute =
  AdminServiceAgreementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminServiceAgreementsRoute,
  } as any)
const AdminDocumentTypesIndexRoute = AdminDocumentTypesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDocumentTypesRoute,
} as any)
const AppSlugTeamRoute = AppSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugSubmissionsRoute = AppSlugSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugSettingsRoute = AppSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugServicesRoute = AppSlugServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppSlugRoute,
} as any)
const AppSlugServiceAgreementsRoute =
  AppSlugServiceAgreementsRouteImport.update({
    id: '/service-agreements',
    path: '/service-agreements',
    getParentRoute: () => AppSlugRoute,
  } as any)
const AppSlugReportsRoute = AppSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppSlugRoute,
} as any)
const AdminServiceAgreementsNewRoute =
  AdminServiceAgreementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminServiceAgreementsRoute,
  } as any)
const AdminServiceAgreementsIdRoute =
  AdminServiceAgreementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminServiceAgreementsRoute,
  } as any)
const AdminDocumentTypesIdRoute = AdminDocumentTypesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDocumentTypesRoute,
} as any)
const AppSlugTeamIndexRoute = AppSlugTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugTeamRoute,
} as any)
const AppSlugSubmissionsIndexRoute = AppSlugSubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugSubmissionsRoute,
} as any)
const AppSlugServicesIndexRoute = AppSlugServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugServicesRoute,
} as any)
const AppSlugServiceAgreementsIndexRoute =
  AppSlugServiceAgreementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSlugServiceAgreementsRoute,
  } as any)
const AppSlugTeamMemberIdRoute = AppSlugTeamMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AppSlugTeamRoute,
} as any)
const AppSlugSubmissionsIdRoute = AppSlugSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSlugSubmissionsRoute,
} as any)
const AppSlugServicesNewRoute = AppSlugServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSlugServicesRoute,
} as any)
const AppSlugServicesIdRoute = AppSlugServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSlugServicesRoute,
} as any)
const AppSlugServiceAgreementsNewRoute =
  AppSlugServiceAgreementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppSlugServiceAgreementsRoute,
  } as any)
const AppSlugServiceAgreementsIdRoute =
  AppSlugServiceAgreementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppSlugServiceAgreementsRoute,
  } as any)
const AppSlugServicesIdIndexRoute = AppSlugServicesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSlugServicesIdRoute,
} as any)
const AppSlugServicesIdServiceAgreementsRoute =
  AppSlugServicesIdServiceAgreementsRouteImport.update({
    id: '/service-agreements',
    path: '/service-agreements',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdApplicationMethodsRoute =
  AppSlugServicesIdApplicationMethodsRouteImport.update({
    id: '/application-methods',
    path: '/application-methods',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdVersionsVersionIdIndexRoute =
  AppSlugServicesIdVersionsVersionIdIndexRouteImport.update({
    id: '/versions/$versionId/',
    path: '/versions/$versionId/',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute =
  AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRouteImport.update({
    id: '/versions/$versionId/service-agreements/',
    path: '/versions/$versionId/service-agreements/',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute =
  AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRouteImport.update({
    id: '/versions/$versionId/application-methods/',
    path: '/versions/$versionId/application-methods/',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute =
  AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRouteImport.update({
    id: '/versions/$versionId/application-methods/new',
    path: '/versions/$versionId/application-methods/new',
    getParentRoute: () => AppSlugServicesIdRoute,
  } as any)
const AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute =
  AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRouteImport.update(
    {
      id: '/versions/$versionId/application-methods/$applicationMethodId',
      path: '/versions/$versionId/application-methods/$applicationMethodId',
      getParentRoute: () => AppSlugServicesIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/document-types': typeof AdminDocumentTypesRouteWithChildren
  '/admin/service-agreements': typeof AdminServiceAgreementsRouteWithChildren
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/document-types/$id': typeof AdminDocumentTypesIdRoute
  '/admin/service-agreements/$id': typeof AdminServiceAgreementsIdRoute
  '/admin/service-agreements/new': typeof AdminServiceAgreementsNewRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/service-agreements': typeof AppSlugServiceAgreementsRouteWithChildren
  '/app/$slug/services': typeof AppSlugServicesRouteWithChildren
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsRouteWithChildren
  '/app/$slug/team': typeof AppSlugTeamRouteWithChildren
  '/admin/document-types/': typeof AdminDocumentTypesIndexRoute
  '/admin/service-agreements/': typeof AdminServiceAgreementsIndexRoute
  '/app/$slug/': typeof AppSlugIndexRoute
  '/app/$slug/service-agreements/$id': typeof AppSlugServiceAgreementsIdRoute
  '/app/$slug/service-agreements/new': typeof AppSlugServiceAgreementsNewRoute
  '/app/$slug/services/$id': typeof AppSlugServicesIdRouteWithChildren
  '/app/$slug/services/new': typeof AppSlugServicesNewRoute
  '/app/$slug/submissions/$id': typeof AppSlugSubmissionsIdRoute
  '/app/$slug/team/$memberId': typeof AppSlugTeamMemberIdRoute
  '/app/$slug/service-agreements/': typeof AppSlugServiceAgreementsIndexRoute
  '/app/$slug/services/': typeof AppSlugServicesIndexRoute
  '/app/$slug/submissions/': typeof AppSlugSubmissionsIndexRoute
  '/app/$slug/team/': typeof AppSlugTeamIndexRoute
  '/app/$slug/services/$id/application-methods': typeof AppSlugServicesIdApplicationMethodsRoute
  '/app/$slug/services/$id/service-agreements': typeof AppSlugServicesIdServiceAgreementsRoute
  '/app/$slug/services/$id/': typeof AppSlugServicesIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId/': typeof AppSlugServicesIdVersionsVersionIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/new': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute
  '/app/$slug/services/$id/versions/$versionId/service-agreements/': typeof AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/account': typeof AppAccountRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/document-types/$id': typeof AdminDocumentTypesIdRoute
  '/admin/service-agreements/$id': typeof AdminServiceAgreementsIdRoute
  '/admin/service-agreements/new': typeof AdminServiceAgreementsNewRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/admin/document-types': typeof AdminDocumentTypesIndexRoute
  '/admin/service-agreements': typeof AdminServiceAgreementsIndexRoute
  '/app/$slug': typeof AppSlugIndexRoute
  '/app/$slug/service-agreements/$id': typeof AppSlugServiceAgreementsIdRoute
  '/app/$slug/service-agreements/new': typeof AppSlugServiceAgreementsNewRoute
  '/app/$slug/services/new': typeof AppSlugServicesNewRoute
  '/app/$slug/submissions/$id': typeof AppSlugSubmissionsIdRoute
  '/app/$slug/team/$memberId': typeof AppSlugTeamMemberIdRoute
  '/app/$slug/service-agreements': typeof AppSlugServiceAgreementsIndexRoute
  '/app/$slug/services': typeof AppSlugServicesIndexRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsIndexRoute
  '/app/$slug/team': typeof AppSlugTeamIndexRoute
  '/app/$slug/services/$id/application-methods': typeof AppSlugServicesIdApplicationMethodsRoute
  '/app/$slug/services/$id/service-agreements': typeof AppSlugServicesIdServiceAgreementsRoute
  '/app/$slug/services/$id': typeof AppSlugServicesIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId': typeof AppSlugServicesIdVersionsVersionIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/new': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute
  '/app/$slug/services/$id/versions/$versionId/service-agreements': typeof AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/admin/document-types': typeof AdminDocumentTypesRouteWithChildren
  '/admin/service-agreements': typeof AdminServiceAgreementsRouteWithChildren
  '/app/$slug': typeof AppSlugRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/document-types/$id': typeof AdminDocumentTypesIdRoute
  '/admin/service-agreements/$id': typeof AdminServiceAgreementsIdRoute
  '/admin/service-agreements/new': typeof AdminServiceAgreementsNewRoute
  '/app/$slug/reports': typeof AppSlugReportsRoute
  '/app/$slug/service-agreements': typeof AppSlugServiceAgreementsRouteWithChildren
  '/app/$slug/services': typeof AppSlugServicesRouteWithChildren
  '/app/$slug/settings': typeof AppSlugSettingsRoute
  '/app/$slug/submissions': typeof AppSlugSubmissionsRouteWithChildren
  '/app/$slug/team': typeof AppSlugTeamRouteWithChildren
  '/admin/document-types/': typeof AdminDocumentTypesIndexRoute
  '/admin/service-agreements/': typeof AdminServiceAgreementsIndexRoute
  '/app/$slug/': typeof AppSlugIndexRoute
  '/app/$slug/service-agreements/$id': typeof AppSlugServiceAgreementsIdRoute
  '/app/$slug/service-agreements/new': typeof AppSlugServiceAgreementsNewRoute
  '/app/$slug/services/$id': typeof AppSlugServicesIdRouteWithChildren
  '/app/$slug/services/new': typeof AppSlugServicesNewRoute
  '/app/$slug/submissions/$id': typeof AppSlugSubmissionsIdRoute
  '/app/$slug/team/$memberId': typeof AppSlugTeamMemberIdRoute
  '/app/$slug/service-agreements/': typeof AppSlugServiceAgreementsIndexRoute
  '/app/$slug/services/': typeof AppSlugServicesIndexRoute
  '/app/$slug/submissions/': typeof AppSlugSubmissionsIndexRoute
  '/app/$slug/team/': typeof AppSlugTeamIndexRoute
  '/app/$slug/services/$id/application-methods': typeof AppSlugServicesIdApplicationMethodsRoute
  '/app/$slug/services/$id/service-agreements': typeof AppSlugServicesIdServiceAgreementsRoute
  '/app/$slug/services/$id/': typeof AppSlugServicesIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId/': typeof AppSlugServicesIdVersionsVersionIdIndexRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/new': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute
  '/app/$slug/services/$id/versions/$versionId/application-methods/': typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute
  '/app/$slug/services/$id/versions/$versionId/service-agreements/': typeof AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/admin/document-types'
    | '/admin/service-agreements'
    | '/app/$slug'
    | '/app/account'
    | '/admin/'
    | '/app/'
    | '/admin/document-types/$id'
    | '/admin/service-agreements/$id'
    | '/admin/service-agreements/new'
    | '/app/$slug/reports'
    | '/app/$slug/service-agreements'
    | '/app/$slug/services'
    | '/app/$slug/settings'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/admin/document-types/'
    | '/admin/service-agreements/'
    | '/app/$slug/'
    | '/app/$slug/service-agreements/$id'
    | '/app/$slug/service-agreements/new'
    | '/app/$slug/services/$id'
    | '/app/$slug/services/new'
    | '/app/$slug/submissions/$id'
    | '/app/$slug/team/$memberId'
    | '/app/$slug/service-agreements/'
    | '/app/$slug/services/'
    | '/app/$slug/submissions/'
    | '/app/$slug/team/'
    | '/app/$slug/services/$id/application-methods'
    | '/app/$slug/services/$id/service-agreements'
    | '/app/$slug/services/$id/'
    | '/app/$slug/services/$id/versions/$versionId/'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/new'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/'
    | '/app/$slug/services/$id/versions/$versionId/service-agreements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/account'
    | '/admin'
    | '/app'
    | '/admin/document-types/$id'
    | '/admin/service-agreements/$id'
    | '/admin/service-agreements/new'
    | '/app/$slug/reports'
    | '/app/$slug/settings'
    | '/admin/document-types'
    | '/admin/service-agreements'
    | '/app/$slug'
    | '/app/$slug/service-agreements/$id'
    | '/app/$slug/service-agreements/new'
    | '/app/$slug/services/new'
    | '/app/$slug/submissions/$id'
    | '/app/$slug/team/$memberId'
    | '/app/$slug/service-agreements'
    | '/app/$slug/services'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/app/$slug/services/$id/application-methods'
    | '/app/$slug/services/$id/service-agreements'
    | '/app/$slug/services/$id'
    | '/app/$slug/services/$id/versions/$versionId'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/new'
    | '/app/$slug/services/$id/versions/$versionId/application-methods'
    | '/app/$slug/services/$id/versions/$versionId/service-agreements'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/admin/document-types'
    | '/admin/service-agreements'
    | '/app/$slug'
    | '/app/account'
    | '/admin/'
    | '/app/'
    | '/admin/document-types/$id'
    | '/admin/service-agreements/$id'
    | '/admin/service-agreements/new'
    | '/app/$slug/reports'
    | '/app/$slug/service-agreements'
    | '/app/$slug/services'
    | '/app/$slug/settings'
    | '/app/$slug/submissions'
    | '/app/$slug/team'
    | '/admin/document-types/'
    | '/admin/service-agreements/'
    | '/app/$slug/'
    | '/app/$slug/service-agreements/$id'
    | '/app/$slug/service-agreements/new'
    | '/app/$slug/services/$id'
    | '/app/$slug/services/new'
    | '/app/$slug/submissions/$id'
    | '/app/$slug/team/$memberId'
    | '/app/$slug/service-agreements/'
    | '/app/$slug/services/'
    | '/app/$slug/submissions/'
    | '/app/$slug/team/'
    | '/app/$slug/services/$id/application-methods'
    | '/app/$slug/services/$id/service-agreements'
    | '/app/$slug/services/$id/'
    | '/app/$slug/services/$id/versions/$versionId/'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/new'
    | '/app/$slug/services/$id/versions/$versionId/application-methods/'
    | '/app/$slug/services/$id/versions/$versionId/service-agreements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/service-agreements': {
      id: '/admin/service-agreements'
      path: '/service-agreements'
      fullPath: '/admin/service-agreements'
      preLoaderRoute: typeof AdminServiceAgreementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-types': {
      id: '/admin/document-types'
      path: '/document-types'
      fullPath: '/admin/document-types'
      preLoaderRoute: typeof AdminDocumentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/$slug/': {
      id: '/app/$slug/'
      path: '/'
      fullPath: '/app/$slug/'
      preLoaderRoute: typeof AppSlugIndexRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/admin/service-agreements/': {
      id: '/admin/service-agreements/'
      path: '/'
      fullPath: '/admin/service-agreements/'
      preLoaderRoute: typeof AdminServiceAgreementsIndexRouteImport
      parentRoute: typeof AdminServiceAgreementsRoute
    }
    '/admin/document-types/': {
      id: '/admin/document-types/'
      path: '/'
      fullPath: '/admin/document-types/'
      preLoaderRoute: typeof AdminDocumentTypesIndexRouteImport
      parentRoute: typeof AdminDocumentTypesRoute
    }
    '/app/$slug/team': {
      id: '/app/$slug/team'
      path: '/team'
      fullPath: '/app/$slug/team'
      preLoaderRoute: typeof AppSlugTeamRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/submissions': {
      id: '/app/$slug/submissions'
      path: '/submissions'
      fullPath: '/app/$slug/submissions'
      preLoaderRoute: typeof AppSlugSubmissionsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/settings': {
      id: '/app/$slug/settings'
      path: '/settings'
      fullPath: '/app/$slug/settings'
      preLoaderRoute: typeof AppSlugSettingsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/services': {
      id: '/app/$slug/services'
      path: '/services'
      fullPath: '/app/$slug/services'
      preLoaderRoute: typeof AppSlugServicesRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/service-agreements': {
      id: '/app/$slug/service-agreements'
      path: '/service-agreements'
      fullPath: '/app/$slug/service-agreements'
      preLoaderRoute: typeof AppSlugServiceAgreementsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/app/$slug/reports': {
      id: '/app/$slug/reports'
      path: '/reports'
      fullPath: '/app/$slug/reports'
      preLoaderRoute: typeof AppSlugReportsRouteImport
      parentRoute: typeof AppSlugRoute
    }
    '/admin/service-agreements/new': {
      id: '/admin/service-agreements/new'
      path: '/new'
      fullPath: '/admin/service-agreements/new'
      preLoaderRoute: typeof AdminServiceAgreementsNewRouteImport
      parentRoute: typeof AdminServiceAgreementsRoute
    }
    '/admin/service-agreements/$id': {
      id: '/admin/service-agreements/$id'
      path: '/$id'
      fullPath: '/admin/service-agreements/$id'
      preLoaderRoute: typeof AdminServiceAgreementsIdRouteImport
      parentRoute: typeof AdminServiceAgreementsRoute
    }
    '/admin/document-types/$id': {
      id: '/admin/document-types/$id'
      path: '/$id'
      fullPath: '/admin/document-types/$id'
      preLoaderRoute: typeof AdminDocumentTypesIdRouteImport
      parentRoute: typeof AdminDocumentTypesRoute
    }
    '/app/$slug/team/': {
      id: '/app/$slug/team/'
      path: '/'
      fullPath: '/app/$slug/team/'
      preLoaderRoute: typeof AppSlugTeamIndexRouteImport
      parentRoute: typeof AppSlugTeamRoute
    }
    '/app/$slug/submissions/': {
      id: '/app/$slug/submissions/'
      path: '/'
      fullPath: '/app/$slug/submissions/'
      preLoaderRoute: typeof AppSlugSubmissionsIndexRouteImport
      parentRoute: typeof AppSlugSubmissionsRoute
    }
    '/app/$slug/services/': {
      id: '/app/$slug/services/'
      path: '/'
      fullPath: '/app/$slug/services/'
      preLoaderRoute: typeof AppSlugServicesIndexRouteImport
      parentRoute: typeof AppSlugServicesRoute
    }
    '/app/$slug/service-agreements/': {
      id: '/app/$slug/service-agreements/'
      path: '/'
      fullPath: '/app/$slug/service-agreements/'
      preLoaderRoute: typeof AppSlugServiceAgreementsIndexRouteImport
      parentRoute: typeof AppSlugServiceAgreementsRoute
    }
    '/app/$slug/team/$memberId': {
      id: '/app/$slug/team/$memberId'
      path: '/$memberId'
      fullPath: '/app/$slug/team/$memberId'
      preLoaderRoute: typeof AppSlugTeamMemberIdRouteImport
      parentRoute: typeof AppSlugTeamRoute
    }
    '/app/$slug/submissions/$id': {
      id: '/app/$slug/submissions/$id'
      path: '/$id'
      fullPath: '/app/$slug/submissions/$id'
      preLoaderRoute: typeof AppSlugSubmissionsIdRouteImport
      parentRoute: typeof AppSlugSubmissionsRoute
    }
    '/app/$slug/services/new': {
      id: '/app/$slug/services/new'
      path: '/new'
      fullPath: '/app/$slug/services/new'
      preLoaderRoute: typeof AppSlugServicesNewRouteImport
      parentRoute: typeof AppSlugServicesRoute
    }
    '/app/$slug/services/$id': {
      id: '/app/$slug/services/$id'
      path: '/$id'
      fullPath: '/app/$slug/services/$id'
      preLoaderRoute: typeof AppSlugServicesIdRouteImport
      parentRoute: typeof AppSlugServicesRoute
    }
    '/app/$slug/service-agreements/new': {
      id: '/app/$slug/service-agreements/new'
      path: '/new'
      fullPath: '/app/$slug/service-agreements/new'
      preLoaderRoute: typeof AppSlugServiceAgreementsNewRouteImport
      parentRoute: typeof AppSlugServiceAgreementsRoute
    }
    '/app/$slug/service-agreements/$id': {
      id: '/app/$slug/service-agreements/$id'
      path: '/$id'
      fullPath: '/app/$slug/service-agreements/$id'
      preLoaderRoute: typeof AppSlugServiceAgreementsIdRouteImport
      parentRoute: typeof AppSlugServiceAgreementsRoute
    }
    '/app/$slug/services/$id/': {
      id: '/app/$slug/services/$id/'
      path: '/'
      fullPath: '/app/$slug/services/$id/'
      preLoaderRoute: typeof AppSlugServicesIdIndexRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/service-agreements': {
      id: '/app/$slug/services/$id/service-agreements'
      path: '/service-agreements'
      fullPath: '/app/$slug/services/$id/service-agreements'
      preLoaderRoute: typeof AppSlugServicesIdServiceAgreementsRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/application-methods': {
      id: '/app/$slug/services/$id/application-methods'
      path: '/application-methods'
      fullPath: '/app/$slug/services/$id/application-methods'
      preLoaderRoute: typeof AppSlugServicesIdApplicationMethodsRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/versions/$versionId/': {
      id: '/app/$slug/services/$id/versions/$versionId/'
      path: '/versions/$versionId'
      fullPath: '/app/$slug/services/$id/versions/$versionId/'
      preLoaderRoute: typeof AppSlugServicesIdVersionsVersionIdIndexRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/versions/$versionId/service-agreements/': {
      id: '/app/$slug/services/$id/versions/$versionId/service-agreements/'
      path: '/versions/$versionId/service-agreements'
      fullPath: '/app/$slug/services/$id/versions/$versionId/service-agreements/'
      preLoaderRoute: typeof AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/versions/$versionId/application-methods/': {
      id: '/app/$slug/services/$id/versions/$versionId/application-methods/'
      path: '/versions/$versionId/application-methods'
      fullPath: '/app/$slug/services/$id/versions/$versionId/application-methods/'
      preLoaderRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/versions/$versionId/application-methods/new': {
      id: '/app/$slug/services/$id/versions/$versionId/application-methods/new'
      path: '/versions/$versionId/application-methods/new'
      fullPath: '/app/$slug/services/$id/versions/$versionId/application-methods/new'
      preLoaderRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
    '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId': {
      id: '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId'
      path: '/versions/$versionId/application-methods/$applicationMethodId'
      fullPath: '/app/$slug/services/$id/versions/$versionId/application-methods/$applicationMethodId'
      preLoaderRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRouteImport
      parentRoute: typeof AppSlugServicesIdRoute
    }
  }
}

interface AdminDocumentTypesRouteChildren {
  AdminDocumentTypesIdRoute: typeof AdminDocumentTypesIdRoute
  AdminDocumentTypesIndexRoute: typeof AdminDocumentTypesIndexRoute
}

const AdminDocumentTypesRouteChildren: AdminDocumentTypesRouteChildren = {
  AdminDocumentTypesIdRoute: AdminDocumentTypesIdRoute,
  AdminDocumentTypesIndexRoute: AdminDocumentTypesIndexRoute,
}

const AdminDocumentTypesRouteWithChildren =
  AdminDocumentTypesRoute._addFileChildren(AdminDocumentTypesRouteChildren)

interface AdminServiceAgreementsRouteChildren {
  AdminServiceAgreementsIdRoute: typeof AdminServiceAgreementsIdRoute
  AdminServiceAgreementsNewRoute: typeof AdminServiceAgreementsNewRoute
  AdminServiceAgreementsIndexRoute: typeof AdminServiceAgreementsIndexRoute
}

const AdminServiceAgreementsRouteChildren: AdminServiceAgreementsRouteChildren =
  {
    AdminServiceAgreementsIdRoute: AdminServiceAgreementsIdRoute,
    AdminServiceAgreementsNewRoute: AdminServiceAgreementsNewRoute,
    AdminServiceAgreementsIndexRoute: AdminServiceAgreementsIndexRoute,
  }

const AdminServiceAgreementsRouteWithChildren =
  AdminServiceAgreementsRoute._addFileChildren(
    AdminServiceAgreementsRouteChildren,
  )

interface AdminRouteChildren {
  AdminDocumentTypesRoute: typeof AdminDocumentTypesRouteWithChildren
  AdminServiceAgreementsRoute: typeof AdminServiceAgreementsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentTypesRoute: AdminDocumentTypesRouteWithChildren,
  AdminServiceAgreementsRoute: AdminServiceAgreementsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppSlugServiceAgreementsRouteChildren {
  AppSlugServiceAgreementsIdRoute: typeof AppSlugServiceAgreementsIdRoute
  AppSlugServiceAgreementsNewRoute: typeof AppSlugServiceAgreementsNewRoute
  AppSlugServiceAgreementsIndexRoute: typeof AppSlugServiceAgreementsIndexRoute
}

const AppSlugServiceAgreementsRouteChildren: AppSlugServiceAgreementsRouteChildren =
  {
    AppSlugServiceAgreementsIdRoute: AppSlugServiceAgreementsIdRoute,
    AppSlugServiceAgreementsNewRoute: AppSlugServiceAgreementsNewRoute,
    AppSlugServiceAgreementsIndexRoute: AppSlugServiceAgreementsIndexRoute,
  }

const AppSlugServiceAgreementsRouteWithChildren =
  AppSlugServiceAgreementsRoute._addFileChildren(
    AppSlugServiceAgreementsRouteChildren,
  )

interface AppSlugServicesIdRouteChildren {
  AppSlugServicesIdApplicationMethodsRoute: typeof AppSlugServicesIdApplicationMethodsRoute
  AppSlugServicesIdServiceAgreementsRoute: typeof AppSlugServicesIdServiceAgreementsRoute
  AppSlugServicesIdIndexRoute: typeof AppSlugServicesIdIndexRoute
  AppSlugServicesIdVersionsVersionIdIndexRoute: typeof AppSlugServicesIdVersionsVersionIdIndexRoute
  AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute
  AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute
  AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute: typeof AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute
  AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute: typeof AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute
}

const AppSlugServicesIdRouteChildren: AppSlugServicesIdRouteChildren = {
  AppSlugServicesIdApplicationMethodsRoute:
    AppSlugServicesIdApplicationMethodsRoute,
  AppSlugServicesIdServiceAgreementsRoute:
    AppSlugServicesIdServiceAgreementsRoute,
  AppSlugServicesIdIndexRoute: AppSlugServicesIdIndexRoute,
  AppSlugServicesIdVersionsVersionIdIndexRoute:
    AppSlugServicesIdVersionsVersionIdIndexRoute,
  AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute:
    AppSlugServicesIdVersionsVersionIdApplicationMethodsApplicationMethodIdRoute,
  AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute:
    AppSlugServicesIdVersionsVersionIdApplicationMethodsNewRoute,
  AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute:
    AppSlugServicesIdVersionsVersionIdApplicationMethodsIndexRoute,
  AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute:
    AppSlugServicesIdVersionsVersionIdServiceAgreementsIndexRoute,
}

const AppSlugServicesIdRouteWithChildren =
  AppSlugServicesIdRoute._addFileChildren(AppSlugServicesIdRouteChildren)

interface AppSlugServicesRouteChildren {
  AppSlugServicesIdRoute: typeof AppSlugServicesIdRouteWithChildren
  AppSlugServicesNewRoute: typeof AppSlugServicesNewRoute
  AppSlugServicesIndexRoute: typeof AppSlugServicesIndexRoute
}

const AppSlugServicesRouteChildren: AppSlugServicesRouteChildren = {
  AppSlugServicesIdRoute: AppSlugServicesIdRouteWithChildren,
  AppSlugServicesNewRoute: AppSlugServicesNewRoute,
  AppSlugServicesIndexRoute: AppSlugServicesIndexRoute,
}

const AppSlugServicesRouteWithChildren = AppSlugServicesRoute._addFileChildren(
  AppSlugServicesRouteChildren,
)

interface AppSlugSubmissionsRouteChildren {
  AppSlugSubmissionsIdRoute: typeof AppSlugSubmissionsIdRoute
  AppSlugSubmissionsIndexRoute: typeof AppSlugSubmissionsIndexRoute
}

const AppSlugSubmissionsRouteChildren: AppSlugSubmissionsRouteChildren = {
  AppSlugSubmissionsIdRoute: AppSlugSubmissionsIdRoute,
  AppSlugSubmissionsIndexRoute: AppSlugSubmissionsIndexRoute,
}

const AppSlugSubmissionsRouteWithChildren =
  AppSlugSubmissionsRoute._addFileChildren(AppSlugSubmissionsRouteChildren)

interface AppSlugTeamRouteChildren {
  AppSlugTeamMemberIdRoute: typeof AppSlugTeamMemberIdRoute
  AppSlugTeamIndexRoute: typeof AppSlugTeamIndexRoute
}

const AppSlugTeamRouteChildren: AppSlugTeamRouteChildren = {
  AppSlugTeamMemberIdRoute: AppSlugTeamMemberIdRoute,
  AppSlugTeamIndexRoute: AppSlugTeamIndexRoute,
}

const AppSlugTeamRouteWithChildren = AppSlugTeamRoute._addFileChildren(
  AppSlugTeamRouteChildren,
)

interface AppSlugRouteChildren {
  AppSlugReportsRoute: typeof AppSlugReportsRoute
  AppSlugServiceAgreementsRoute: typeof AppSlugServiceAgreementsRouteWithChildren
  AppSlugServicesRoute: typeof AppSlugServicesRouteWithChildren
  AppSlugSettingsRoute: typeof AppSlugSettingsRoute
  AppSlugSubmissionsRoute: typeof AppSlugSubmissionsRouteWithChildren
  AppSlugTeamRoute: typeof AppSlugTeamRouteWithChildren
  AppSlugIndexRoute: typeof AppSlugIndexRoute
}

const AppSlugRouteChildren: AppSlugRouteChildren = {
  AppSlugReportsRoute: AppSlugReportsRoute,
  AppSlugServiceAgreementsRoute: AppSlugServiceAgreementsRouteWithChildren,
  AppSlugServicesRoute: AppSlugServicesRouteWithChildren,
  AppSlugSettingsRoute: AppSlugSettingsRoute,
  AppSlugSubmissionsRoute: AppSlugSubmissionsRouteWithChildren,
  AppSlugTeamRoute: AppSlugTeamRouteWithChildren,
  AppSlugIndexRoute: AppSlugIndexRoute,
}

const AppSlugRouteWithChildren =
  AppSlugRoute._addFileChildren(AppSlugRouteChildren)

interface AppRouteChildren {
  AppSlugRoute: typeof AppSlugRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSlugRoute: AppSlugRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
