apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-auth
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.app.oidc.clientSecret | quote }}
  SESSION_SECRET: {{ .Values.app.session.secret | quote }}
